<?php

namespace ItkEnter\DataModels\Command;

use ItkEnter\DataModels\Config;
use ItkEnter\DataModels\Generator\ContextJsonldGenerator;
use ItkEnter\DataModels\Generator\ExamplesGenerator;
use ItkEnter\DataModels\Generator\ModelReadmeGenerator;
use ItkEnter\DataModels\Generator\ModelYamlGenerator;
use ItkEnter\DataModels\Generator\RootReadmeIndexGenerator;
use ItkEnter\DataModels\Generator\SchemaSqlGenerator;
use ItkEnter\DataModels\Generator\SpecMdGenerator;
use ItkEnter\DataModels\Generator\SwaggerYamlGenerator;
use ItkEnter\DataModels\Generator\TwigFactory;
use ItkEnter\DataModels\Model\DereferencedModel;
use ItkEnter\DataModels\Model\ModelFinder;
use ItkEnter\DataModels\Model\ModelLoader;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Yaml\Yaml;

#[AsCommand(name: 'generate', description: "Generate a model's files, or all models if none given")]
final class GenerateCommand extends Command
{
    private const JSON_FLAGS = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;
    private const YAML_HEADER = "# generated by `task generate` — do not edit\n\n";
    private const SQL_HEADER = "-- generated by `task generate` — do not edit\n";
    private const MD_HEADER = "<!-- generated by `task generate` — do not edit -->\n\n";

    // doc/spec.md's per-property lines are long, upstream-sourced free
    // text with plain URLs in them — that's the SDM property-list
    // convention it deliberately follows (data-models-PLAN.md's Findings),
    // not a style violation to fix.
    private const SPEC_MD_HEADER = "<!-- generated by `task generate` — do not edit -->\n".
        "<!-- markdownlint-disable MD013 MD034 -->\n\n";

    public function __construct(private readonly string $repoRoot)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->addArgument('model', InputArgument::OPTIONAL, 'The model to generate; all models if omitted');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $config = Config::fromFile($this->repoRoot.'/config.yaml');
        $finder = new ModelFinder($this->repoRoot);
        $loader = new ModelLoader($this->repoRoot, $config->commonSchemaRefUrl);
        $filesystem = new Filesystem();

        $modelName = $input->getArgument('model');
        $allModels = array_map($loader->load(...), $finder->all());

        if (null !== $modelName && [] === array_filter($allModels, static fn (DereferencedModel $m) => $m->folder->name === $modelName)) {
            $output->writeln("<error>No such model: {$modelName}</error>");

            return Command::FAILURE;
        }

        $twig = TwigFactory::create($this->repoRoot);
        $examplesGenerator = new ExamplesGenerator($config);
        $modelYamlGenerator = new ModelYamlGenerator();
        $swaggerGenerator = new SwaggerYamlGenerator();
        $schemaSqlGenerator = new SchemaSqlGenerator();
        $specGenerator = new SpecMdGenerator($twig);
        $readmeGenerator = new ModelReadmeGenerator($twig, $config);

        foreach ($allModels as $model) {
            if (null !== $modelName && $model->folder->name !== $modelName) {
                continue;
            }

            $this->writeModelFiles(
                $filesystem,
                $model,
                $examplesGenerator,
                $modelYamlGenerator,
                $swaggerGenerator,
                $schemaSqlGenerator,
                $specGenerator,
                $readmeGenerator,
            );
            $output->writeln("<info>{$model->folder->name}: generated</info>");
        }

        $this->writeSubjectContexts($filesystem, $config, $allModels);
        $this->updateRootReadme($filesystem, $config, $allModels);

        return Command::SUCCESS;
    }

    /**
     * @param DereferencedModel[] $allModels
     */
    private function writeSubjectContexts(Filesystem $filesystem, Config $config, array $allModels): void
    {
        $bySubject = [];
        foreach ($allModels as $model) {
            $bySubject[$model->folder->subject][] = $model;
        }

        $generator = new ContextJsonldGenerator($config);
        foreach ($bySubject as $subject => $models) {
            $filesystem->dumpFile("{$this->repoRoot}/{$subject}/context.jsonld", $generator->generate($subject, $models));
        }
    }

    /**
     * @param DereferencedModel[] $allModels
     */
    private function updateRootReadme(Filesystem $filesystem, Config $config, array $allModels): void
    {
        $path = $this->repoRoot.'/README.md';
        $readme = file_get_contents($path);
        $generator = new RootReadmeIndexGenerator($config);
        $filesystem->dumpFile($path, $generator->update($readme, $allModels));
    }

    private function writeModelFiles(
        Filesystem $filesystem,
        DereferencedModel $model,
        ExamplesGenerator $examplesGenerator,
        ModelYamlGenerator $modelYamlGenerator,
        SwaggerYamlGenerator $swaggerGenerator,
        SchemaSqlGenerator $schemaSqlGenerator,
        SpecMdGenerator $specGenerator,
        ModelReadmeGenerator $readmeGenerator,
    ): void {
        $path = $model->folder->path;

        foreach ($examplesGenerator->generate($model) as $filename => $data) {
            $filesystem->dumpFile("{$path}/examples/{$filename}", json_encode($data, self::JSON_FLAGS)."\n");
        }

        $filesystem->dumpFile("{$path}/model.yaml", self::YAML_HEADER.Yaml::dump($modelYamlGenerator->generate($model), 32, 2));
        $filesystem->dumpFile("{$path}/swagger.yaml", self::YAML_HEADER.Yaml::dump($swaggerGenerator->generate($model), 32, 2));
        $filesystem->dumpFile("{$path}/schema.sql", self::SQL_HEADER.$schemaSqlGenerator->generate($model)."\n");
        $filesystem->dumpFile("{$path}/doc/spec.md", self::SPEC_MD_HEADER.$specGenerator->generate($model));
        $filesystem->dumpFile("{$path}/README.md", self::MD_HEADER.$readmeGenerator->generate($model));
    }
}
