<?php

namespace ItkEnter\DataModels\Generator;

use ItkEnter\DataModels\Config;
use ItkEnter\DataModels\Model\DereferencedModel;
use ItkEnter\DataModels\Model\ModelFinder;
use ItkEnter\DataModels\Model\ModelLoader;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Yaml\Yaml;

/**
 * Runs every generator and writes their output, for one model or all of them. `bin/datamodels generate` and
 * `bin/datamodels release` both go through this, so a release checks
 * exactly what `task generate` would have written.
 */
final class RepositoryGenerator
{
    private const JSON_FLAGS = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;
    private const YAML_HEADER = "# generated by `task generate` — do not edit\n\n";
    private const SQL_HEADER = "-- generated by `task generate` — do not edit\n";
    private const MD_HEADER = "<!-- generated by `task generate` — do not edit -->\n\n";

    // doc/spec.md's per-property lines are long, upstream-sourced free
    // text with plain URLs in them — that's the SDM property-list
    // convention it deliberately follows,
    // not a style violation to fix.
    private const SPEC_MD_HEADER = "<!-- generated by `task generate` — do not edit -->\n".
        "<!-- markdownlint-disable MD013 MD034 -->\n\n";

    private readonly Config $config;
    private readonly Filesystem $filesystem;
    private readonly ExamplesGenerator $examplesGenerator;
    private readonly ModelYamlGenerator $modelYamlGenerator;
    private readonly SwaggerYamlGenerator $swaggerGenerator;
    private readonly SchemaSqlGenerator $schemaSqlGenerator;
    private readonly SpecMdGenerator $specGenerator;
    private readonly ModelReadmeGenerator $readmeGenerator;

    public function __construct(private readonly string $repoRoot)
    {
        $this->config = Config::fromFile($this->repoRoot.'/config.yaml');
        $this->filesystem = new Filesystem();

        $twig = TwigFactory::create($this->repoRoot);
        $this->examplesGenerator = new ExamplesGenerator($this->config);
        $this->modelYamlGenerator = new ModelYamlGenerator();
        $this->swaggerGenerator = new SwaggerYamlGenerator();
        $this->schemaSqlGenerator = new SchemaSqlGenerator();
        $this->specGenerator = new SpecMdGenerator($twig);
        $this->readmeGenerator = new ModelReadmeGenerator($twig, $this->config);
    }

    /**
     * @return string[] the names of the models actually (re)generated
     *
     * @throws \RuntimeException if $modelName is given but no such model exists
     */
    public function generate(?string $modelName = null): array
    {
        $loader = new ModelLoader($this->repoRoot, $this->config->commonSchemaRefUrl);
        $allModels = array_map($loader->load(...), (new ModelFinder($this->repoRoot))->all());

        if (null !== $modelName && [] === array_filter($allModels, static fn (DereferencedModel $m) => $m->folder->name === $modelName)) {
            throw new \RuntimeException("No such model: {$modelName}");
        }

        $generated = [];
        foreach ($allModels as $model) {
            if (null !== $modelName && $model->folder->name !== $modelName) {
                continue;
            }

            $this->writeModelFiles($model);
            $generated[] = $model->folder->name;
        }

        $this->writeSubjectContexts($allModels);
        $this->updateRootReadme($allModels);

        return $generated;
    }

    /**
     * @param DereferencedModel[] $allModels
     */
    private function writeSubjectContexts(array $allModels): void
    {
        $bySubject = [];
        foreach ($allModels as $model) {
            $bySubject[$model->folder->subject][] = $model;
        }

        $generator = new ContextJsonldGenerator($this->config);
        foreach ($bySubject as $subject => $models) {
            $this->filesystem->dumpFile("{$this->repoRoot}/{$subject}/context.jsonld", $generator->generate($subject, $models));
        }
    }

    /**
     * @param DereferencedModel[] $allModels
     */
    private function updateRootReadme(array $allModels): void
    {
        $path = $this->repoRoot.'/README.md';
        $readme = file_get_contents($path);
        $generator = new RootReadmeIndexGenerator($this->config);
        $this->filesystem->dumpFile($path, $generator->update($readme, $allModels));
    }

    private function writeModelFiles(DereferencedModel $model): void
    {
        $path = $model->folder->path;

        foreach ($this->examplesGenerator->generate($model) as $filename => $data) {
            $this->filesystem->dumpFile("{$path}/examples/{$filename}", json_encode($data, self::JSON_FLAGS)."\n");
        }

        $this->filesystem->dumpFile("{$path}/model.yaml", self::YAML_HEADER.Yaml::dump($this->modelYamlGenerator->generate($model), 32, 2));
        $this->filesystem->dumpFile("{$path}/swagger.yaml", self::YAML_HEADER.Yaml::dump($this->swaggerGenerator->generate($model), 32, 2));
        $this->filesystem->dumpFile("{$path}/schema.sql", self::SQL_HEADER.$this->schemaSqlGenerator->generate($model)."\n");
        $this->filesystem->dumpFile("{$path}/doc/spec.md", self::SPEC_MD_HEADER.$this->specGenerator->generate($model));
        $this->filesystem->dumpFile("{$path}/README.md", self::MD_HEADER.$this->readmeGenerator->generate($model));
    }
}
